name: Run isort
on:
  pull_request:
    branches: [ master, develop, feature/*, release/*, hotfix/*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Set up Python environment
        run: pip install isort~=8.0.1
      - name: Run isort
        run: isort src --check-only
